load("dummy_files.bzl", "add_dummy_files")







genrule(
    name = "dummuy-script",
    srcs = [
        "script.go",
        "script.py",
    ],
    outs = ["dummy.py"],
    cmd = """
		touch $@




	""",
)








